server:
  port: 8080

spring:
  datasource:
    ssm:
      driver-class-name: com.mysql.jdbc.Driver
      password: 9e7gyLdYN7MiracpFqmZ
      url: jdbc:mysql://localhost:3306/ws?serverTimezone=GMT%2B8
      username: root

logging:
  config: classpath:log4j2.xml

